# This is a basic workflow that is manually triggered

name: generate lists

on:
  workflow_dispatch:

jobs:
  build:
    name: Build list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Sync dependencies
        run: uv sync

      - name: Run script
        run: uv run ./disposable.py --source-map --skip-scrape --skip-src 'Tempmailo'
