name: validate commit

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync

      - name: Run validation
        run: uv run make validate

      - name: Run tests
        run: uv run make test

      - name: Run verify script
        run: uv run python tools/verify_data.py --github

      - name: Run disposable script
        run: uv run python disposable.py --help